jobs:
  fmt:
    command: black . --exclude venv
    targets:
      - all

  yenv:
    function: yenv:main
    context:
      yenv-file: environment.yml
      env-targets:
        - pyimport

  main-env:
    command: export ${cat pyimport.env}
  
  template:
    command: templ8 ./template.yml .

  docs:
    command: python setup.py updateDocs
  
  clean:
    function: clean:main
    context:
      clean_dirs:
        - build
        - dist
        - pyimport.egg-info

  pypi-upload:
    function: pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz

  purge:
    command: purge pyimport joellefkowitz

projects:
  pyimport:
    path: ../pyimport

routines:
  pre-release:
    - fmt
    - clean
    - docs


